# Generated by Django 5.0.3 on 2024-03-24 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctionId', models.CharField(max_length=6)),
                ('auctionName', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('initialPoint', models.IntegerField(default=0)),
                ('maxBid', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=50)),
                ('status', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminId', models.CharField(max_length=4)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=128)),
                ('subscription', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.SmallIntegerField()),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerId', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('battingStyle', models.TextField(null=True)),
                ('bowlingStyle', models.TextField(null=True)),
                ('gender', models.SmallIntegerField()),
                ('image', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auction_teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('auctionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.auction')),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='team',
            field=models.ManyToManyField(through='appdata.Auction_teams', to='appdata.auction'),
        ),
        migrations.AddField(
            model_name='auction',
            name='adminId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appdata.auctionadmin'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamId', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=128)),
                ('logo', models.TextField(default=None, null=True)),
                ('captainId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='appdata.player')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=0)),
                ('auctionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.auction')),
                ('playerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.player')),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appdata.team')),
            ],
        ),
        migrations.AddField(
            model_name='auction_teams',
            name='teamId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.team'),
        ),
    ]
