# Generated by Django 5.0.3 on 2024-03-27 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='captainId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='appdata.player'),
        ),
    ]
