# Generated by Django 5.0.3 on 2024-03-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='player/'),
        ),
    ]
