# Generated by Django 5.0.3 on 2024-03-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0002_alter_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionadmin',
            name='password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
