# Generated by Django 5.0.3 on 2024-03-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0003_alter_auctionadmin_password_alter_login_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auctionName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='auctionadmin',
            name='adminId',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='auctionadmin',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='playerId',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamId',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
