# Generated by Django 5.0.3 on 2024-03-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0004_alter_auction_auctionname_alter_auctionadmin_adminid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionadmin',
            name='adminId',
            field=models.CharField(max_length=40),
        ),
    ]
