# Generated by Django 5.0.3 on 2024-03-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0005_alter_auctionadmin_adminid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionadmin',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='playerId',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamId',
            field=models.CharField(max_length=6),
        ),
    ]
