# Generated by Django 5.0.3 on 2024-03-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0006_alter_auctionadmin_email_alter_login_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionadmin',
            name='adminId',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='auctionadmin',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
