# Generated by Django 5.0.3 on 2024-03-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0007_alter_auctionadmin_adminid_alter_auctionadmin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamId',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
