# Generated by Django 5.0.3 on 2024-03-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0008_alter_team_email_alter_team_teamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='playerId',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
