# Generated by Django 5.0.3 on 2024-03-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0009_alter_login_email_alter_player_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auctionId',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
