# Generated by Django 5.0.3 on 2024-03-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0011_alter_player_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.SmallIntegerField(null=True),
        ),
    ]
