# Generated by Django 5.0.3 on 2024-03-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0012_alter_player_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='battingStyle',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='bowlingStyle',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='player/'),
        ),
    ]
