# Generated by Django 5.0.3 on 2024-03-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0013_alter_player_battingstyle_alter_player_bowlingstyle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auctionId',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamId',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
