# Generated by Django 5.0.3 on 2024-03-24 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0014_alter_auction_auctionid_alter_team_teamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='captainId',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appdata.player'),
        ),
    ]
