# Generated by Django 5.0.3 on 2024-03-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0015_alter_team_captainid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionadmin',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
