# Generated by Django 5.0.3 on 2024-03-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0016_auctionadmin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(default=None, null=True, upload_to='team/'),
        ),
    ]
