# Generated by Django 5.0.3 on 2024-04-02 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0018_alter_auctionplayer_teamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionplayer',
            name='teamId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appdata.team'),
        ),
    ]
