# Generated by Django 5.0.3 on 2024-04-06 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0021_curruntplayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionadmin',
            old_name='adminId',
            new_name='adminid',
        ),
    ]
