# Generated by Django 5.0.3 on 2024-03-17 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=4)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.SmallIntegerField(max_length=1)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=200)),
                ('role', models.IntegerField(max_length=1)),
                ('age', models.IntegerField(max_length=2)),
                ('batting_style', models.TextField()),
                ('bowling_style', models.TextField()),
                ('gender', models.SmallIntegerField(max_length=1)),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=128)),
                ('points', models.IntegerField(default=0)),
                ('logo', models.TextField()),
                ('captain_id', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('auction_id', models.CharField(max_length=6)),
                ('auction_name', models.CharField(max_length=50)),
                ('initial_point', models.IntegerField()),
                ('max_bid', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('status', models.SmallIntegerField(max_length=1)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playerauction.auction_admin')),
            ],
        ),
        migrations.CreateModel(
            name='Auction_player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(max_length=1)),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerauction.auction')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerauction.player')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='playerauction.team')),
            ],
        ),
    ]
