# Generated by Django 5.0.3 on 2024-03-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerauction', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auction_Admin',
            new_name='AuctionAdmin',
        ),
        migrations.RenameModel(
            old_name='Auction_player',
            new_name='AuctionPlayer',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='admin_id',
            new_name='adminId',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='auction_id',
            new_name='auctionId',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='auction_name',
            new_name='auctionName',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='initial_point',
            new_name='initialPoint',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='max_bid',
            new_name='maxBid',
        ),
        migrations.RenameField(
            model_name='auctionadmin',
            old_name='admin_id',
            new_name='adminId',
        ),
        migrations.RenameField(
            model_name='auctionplayer',
            old_name='auction_id',
            new_name='auctionId',
        ),
        migrations.RenameField(
            model_name='auctionplayer',
            old_name='player_id',
            new_name='playerId',
        ),
        migrations.RenameField(
            model_name='auctionplayer',
            old_name='team_id',
            new_name='teamId',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='batting_style',
            new_name='battingStyle',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='bowling_style',
            new_name='bowlingStyle',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_id',
            new_name='playerId',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='captain_id',
            new_name='teamId',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_id',
        ),
        migrations.AddField(
            model_name='team',
            name='captainId',
            field=models.CharField(default=None, max_length=6),
        ),
    ]
