# Generated by Django 5.0.3 on 2024-03-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerauction', '0002_rename_auction_admin_auctionadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
