# Generated by Django 5.0.3 on 2024-03-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerauction', '0005_alter_login_email_alter_player_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='battingStyle',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='bowlingStyle',
            field=models.TextField(null=True),
        ),
    ]
