# Generated by Django 5.0.3 on 2024-03-22 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerauction', '0006_alter_player_battingstyle_alter_player_bowlingstyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('auctionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerauction.auction')),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerauction.team')),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='team',
            field=models.ManyToManyField(through='playerauction.Auction_teams', to='playerauction.auction'),
        ),
    ]
