# Generated by Django 5.0.3 on 2024-03-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerauction', '0008_alter_auction_status_alter_auctionplayer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(),
        ),
    ]
